export interface Ticket {
  id: string;
  titulo: string;
  descricao: string;
  clienteId: string;
  clienteNome: string;
  criadorId: string;
  criadorNome: string;
  ownerId?: string;
  ownerNome?: string;
  distribuidoraId?: string;
  distribuidoraNome?: string;
  pedidoId?: string;
  pedidoNumero?: string;
  status: 'open' | 'assigned' | 'resolved' | 'closed';
  prioridade: 'baixa' | 'media' | 'alta' | 'urgente';
  dataCriacao: string;
  dataAtualizacao: string;
}

export const mockTickets: Ticket[] = [
  // Open tickets
  {
    id: '1',
    titulo: 'Problema com entrega do pedido',
    descricao: 'Cliente reportou que o pedido PED-2024-003 não foi entregue no prazo. Necessário verificar com a distribuidora o status da entrega e informar previsão atualizada.',
    clienteId: '1',
    clienteNome: 'João Silva',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    distribuidoraId: '1',
    distribuidoraNome: 'Distribuidora Nacional S.A.',
    pedidoId: '3',
    pedidoNumero: 'PED-2024-003',
    status: 'open',
    prioridade: 'alta',
    dataCriacao: '2024-10-22',
    dataAtualizacao: '2024-10-22',
  },
  {
    id: '2',
    titulo: 'Solicitação de alteração de dados cadastrais',
    descricao: 'Cliente solicitou atualização do endereço de entrega e telefone de contato. Novos dados: Rua das Flores, 123 - São Paulo, SP. Tel: (11) 91234-5678',
    clienteId: '2',
    clienteNome: 'Maria Santos',
    criadorId: 'user2',
    criadorNome: 'Regular User',
    status: 'open',
    prioridade: 'media',
    dataCriacao: '2024-10-23',
    dataAtualizacao: '2024-10-23',
  },
  {
    id: '3',
    titulo: 'Dúvida sobre produto',
    descricao: 'Cliente tem dúvidas sobre as especificações técnicas do Produto Premium A e compatibilidade com sistemas existentes.',
    clienteId: '1',
    clienteNome: 'João Silva',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    status: 'open',
    prioridade: 'baixa',
    dataCriacao: '2024-10-24',
    dataAtualizacao: '2024-10-24',
  },
  {
    id: '4',
    titulo: 'Erro no valor do pedido',
    descricao: 'Cliente reportou divergência no valor total do pedido PED-2024-015. Verificar se os descontos foram aplicados corretamente.',
    clienteId: '1',
    clienteNome: 'João Silva',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    pedidoId: '15',
    pedidoNumero: 'PED-2024-015',
    status: 'open',
    prioridade: 'urgente',
    dataCriacao: '2024-10-25',
    dataAtualizacao: '2024-10-25',
  },

  // Assigned tickets
  {
    id: '5',
    titulo: 'Produto com defeito',
    descricao: 'Cliente reportou que o Produto Smart F apresentou defeito após 2 dias de uso. Produto coberto pela garantia. Necessário agendar troca.',
    clienteId: '1',
    clienteNome: 'João Silva',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    ownerId: 'owner1',
    ownerNome: 'Suporte Técnico',
    pedidoId: '6',
    pedidoNumero: 'PED-2024-006',
    status: 'assigned',
    prioridade: 'alta',
    dataCriacao: '2024-10-20',
    dataAtualizacao: '2024-10-21',
  },
  {
    id: '6',
    titulo: 'Atraso na distribuição',
    descricao: 'Distribuidora Sul Distribuidora Ltda está com atraso de 5 dias em pedidos. Verificar motivo e estabelecer novo prazo.',
    clienteId: '2',
    clienteNome: 'Maria Santos',
    criadorId: 'user2',
    criadorNome: 'Regular User',
    ownerId: 'owner2',
    ownerNome: 'Gerente de Logística',
    distribuidoraId: '2',
    distribuidoraNome: 'Sul Distribuidora Ltda',
    status: 'assigned',
    prioridade: 'alta',
    dataCriacao: '2024-10-18',
    dataAtualizacao: '2024-10-20',
  },
  {
    id: '7',
    titulo: 'Solicitação de reembolso',
    descricao: 'Cliente solicitou reembolso do pedido PED-2024-009 que foi cancelado. Valor total: R$ 2.499,99',
    clienteId: '1',
    clienteNome: 'João Silva',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    ownerId: 'owner3',
    ownerNome: 'Financeiro',
    pedidoId: '9',
    pedidoNumero: 'PED-2024-009',
    status: 'assigned',
    prioridade: 'media',
    dataCriacao: '2024-10-19',
    dataAtualizacao: '2024-10-21',
  },
  {
    id: '8',
    titulo: 'Integração com sistema do cliente',
    descricao: 'Cliente necessita de suporte para integração da API com sistema interno. Requer documentação técnica e exemplos de código.',
    clienteId: '3',
    clienteNome: 'Pedro Oliveira',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    ownerId: 'owner1',
    ownerNome: 'Suporte Técnico',
    status: 'assigned',
    prioridade: 'media',
    dataCriacao: '2024-10-17',
    dataAtualizacao: '2024-10-19',
  },

  // Resolved tickets
  {
    id: '9',
    titulo: 'Nota fiscal não recebida',
    descricao: 'Cliente não recebeu nota fiscal do pedido PED-2024-001. Nota foi reenviada por email.',
    clienteId: '1',
    clienteNome: 'João Silva',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    ownerId: 'owner3',
    ownerNome: 'Financeiro',
    pedidoId: '1',
    pedidoNumero: 'PED-2024-001',
    status: 'resolved',
    prioridade: 'baixa',
    dataCriacao: '2024-10-15',
    dataAtualizacao: '2024-10-16',
  },
  {
    id: '10',
    titulo: 'Informações sobre novo produto',
    descricao: 'Cliente solicitou informações sobre lançamento de novos produtos. Catálogo 2025 enviado por email.',
    clienteId: '4',
    clienteNome: 'Ana Costa',
    criadorId: 'user2',
    criadorNome: 'Regular User',
    ownerId: 'owner1',
    ownerNome: 'Suporte Técnico',
    status: 'resolved',
    prioridade: 'baixa',
    dataCriacao: '2024-10-14',
    dataAtualizacao: '2024-10-15',
  },
  {
    id: '11',
    titulo: 'Problema no login do portal',
    descricao: 'Cliente reportou erro ao fazer login no portal. Senha resetada e novo acesso enviado.',
    clienteId: '5',
    clienteNome: 'Carlos Ferreira',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    ownerId: 'owner1',
    ownerNome: 'Suporte Técnico',
    status: 'resolved',
    prioridade: 'media',
    dataCriacao: '2024-10-12',
    dataAtualizacao: '2024-10-13',
  },
  {
    id: '12',
    titulo: 'Pedido duplicado por engano',
    descricao: 'Cliente realizou pedido duplicado por engano. Um dos pedidos foi cancelado sem custos.',
    clienteId: '1',
    clienteNome: 'João Silva',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    ownerId: 'owner2',
    ownerNome: 'Gerente de Logística',
    status: 'resolved',
    prioridade: 'media',
    dataCriacao: '2024-10-10',
    dataAtualizacao: '2024-10-11',
  },

  // Closed tickets
  {
    id: '13',
    titulo: 'Consultoria sobre melhor produto',
    descricao: 'Cliente solicitou consultoria para escolher o melhor produto para sua necessidade. Recomendação feita e pedido realizado.',
    clienteId: '2',
    clienteNome: 'Maria Santos',
    criadorId: 'user2',
    criadorNome: 'Regular User',
    ownerId: 'owner1',
    ownerNome: 'Suporte Técnico',
    status: 'closed',
    prioridade: 'baixa',
    dataCriacao: '2024-10-05',
    dataAtualizacao: '2024-10-07',
  },
  {
    id: '14',
    titulo: 'Troca de produto realizada',
    descricao: 'Produto com defeito foi trocado com sucesso. Cliente confirmou recebimento e satisfação.',
    clienteId: '1',
    clienteNome: 'João Silva',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    ownerId: 'owner1',
    ownerNome: 'Suporte Técnico',
    status: 'closed',
    prioridade: 'alta',
    dataCriacao: '2024-10-01',
    dataAtualizacao: '2024-10-05',
  },
  {
    id: '15',
    titulo: 'Atualização de contrato',
    descricao: 'Cliente solicitou atualização nos termos do contrato. Novo contrato assinado e arquivado.',
    clienteId: '3',
    clienteNome: 'Pedro Oliveira',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    ownerId: 'owner3',
    ownerNome: 'Financeiro',
    status: 'closed',
    prioridade: 'media',
    dataCriacao: '2024-09-28',
    dataAtualizacao: '2024-10-02',
  },
  {
    id: '16',
    titulo: 'Desconto aplicado incorretamente',
    descricao: 'Desconto foi aplicado incorretamente no pedido. Valor ajustado e nota fiscal corrigida emitida.',
    clienteId: '1',
    clienteNome: 'João Silva',
    criadorId: 'user1',
    criadorNome: 'Admin User',
    ownerId: 'owner3',
    ownerNome: 'Financeiro',
    pedidoId: '2',
    pedidoNumero: 'PED-2024-002',
    status: 'closed',
    prioridade: 'media',
    dataCriacao: '2024-09-25',
    dataAtualizacao: '2024-09-27',
  },
  {
    id: '17',
    titulo: 'Solicitação de documentos fiscais',
    descricao: 'Cliente solicitou segunda via de documentos fiscais do último trimestre. Documentos enviados por email.',
    clienteId: '4',
    clienteNome: 'Ana Costa',
    criadorId: 'user2',
    criadorNome: 'Regular User',
    ownerId: 'owner3',
    ownerNome: 'Financeiro',
    status: 'closed',
    prioridade: 'baixa',
    dataCriacao: '2024-09-20',
    dataAtualizacao: '2024-09-22',
  },
];
