export interface Job {
  id: string;
  nome: string;
  descricao: string;
  dataExecucao: string;
  resultado: 'success' | 'error';
  duracao: number; // in seconds
  mensagemErro?: string;
  tipo: string; // e.g., 'sync', 'import', 'export', 'backup', 'cleanup'
  empresa: string;
  distribuidora: string;
}

export const mockJobs: Job[] = [
  {
    id: '1',
    nome: 'Sincronização de Produtos',
    descricao: 'Sincronizar produtos com sistema externo',
    dataExecucao: '2025-10-22T14:30:00',
    resultado: 'success',
    duracao: 45,
    tipo: 'sync',
    empresa: 'Empresa ABC',
    distribuidora: 'Distribuidora Nacional S.A.',
  },
  {
    id: '2',
    nome: 'Importação de Clientes',
    descricao: 'Importar clientes do arquivo CSV',
    dataExecucao: '2025-10-22T13:15:00',
    resultado: 'success',
    duracao: 120,
    tipo: 'import',
    empresa: 'Tech Solutions',
    distribuidora: 'Sul Distribuidora Ltda',
  },
  {
    id: '3',
    nome: 'Backup de Banco de Dados',
    descricao: 'Realizar backup completo do banco de dados',
    dataExecucao: '2025-10-22T12:00:00',
    resultado: 'success',
    duracao: 300,
    tipo: 'backup',
    empresa: 'Digital First',
    distribuidora: 'Nordeste Comércio e Distribuição',
  },
  {
    id: '4',
    nome: 'Limpeza de Logs Antigos',
    descricao: 'Remover logs com mais de 90 dias',
    dataExecucao: '2025-10-22T11:45:00',
    resultado: 'error',
    duracao: 15,
    mensagemErro: 'Falha ao acessar o diretório de logs',
    tipo: 'cleanup',
    empresa: 'Startup Inovadora',
    distribuidora: 'Centro-Oeste Distribuidora',
  },
  {
    id: '5',
    nome: 'Exportação de Relatórios',
    descricao: 'Exportar relatórios mensais para PDF',
    dataExecucao: '2025-10-22T10:30:00',
    resultado: 'success',
    duracao: 180,
    tipo: 'export',
    empresa: 'Empresa ABC',
    distribuidora: 'Norte Logística e Distribuição',
  },
  {
    id: '6',
    nome: 'Sincronização de Estoque',
    descricao: 'Atualizar estoque com dados das distribuidoras',
    dataExecucao: '2025-10-22T09:00:00',
    resultado: 'error',
    duracao: 30,
    mensagemErro: 'Timeout na conexão com API da distribuidora',
    tipo: 'sync',
    empresa: 'Tech Solutions',
    distribuidora: 'Distribuidora Nacional S.A.',
  },
  {
    id: '7',
    nome: 'Processamento de Pedidos',
    descricao: 'Processar pedidos pendentes em lote',
    dataExecucao: '2025-10-22T08:15:00',
    resultado: 'success',
    duracao: 90,
    tipo: 'sync',
    empresa: 'Digital First',
    distribuidora: 'Sul Distribuidora Ltda',
  },
  {
    id: '8',
    nome: 'Importação de Produtos',
    descricao: 'Importar catálogo de produtos atualizado',
    dataExecucao: '2025-10-22T07:00:00',
    resultado: 'success',
    duracao: 240,
    tipo: 'import',
    empresa: 'Commerce Plus',
    distribuidora: 'Nordeste Comércio e Distribuição',
  },
  {
    id: '9',
    nome: 'Backup Incremental',
    descricao: 'Backup incremental de alterações',
    dataExecucao: '2025-10-22T06:00:00',
    resultado: 'success',
    duracao: 60,
    tipo: 'backup',
    empresa: 'Startup Inovadora',
    distribuidora: 'Norte Logística e Distribuição',
  },
  {
    id: '10',
    nome: 'Validação de Dados',
    descricao: 'Validar integridade dos dados cadastrais',
    dataExecucao: '2025-10-22T05:30:00',
    resultado: 'error',
    duracao: 20,
    mensagemErro: 'Inconsistências encontradas em 15 registros',
    tipo: 'sync',
    empresa: 'Empresa ABC',
    distribuidora: 'Centro-Oeste Distribuidora',
  },
  {
    id: '11',
    nome: 'Sincronização de Preços',
    descricao: 'Atualizar tabela de preços',
    dataExecucao: '2025-10-22T04:00:00',
    resultado: 'success',
    duracao: 45,
    tipo: 'sync',
    empresa: 'Tech Solutions',
    distribuidora: 'Distribuidora Nacional S.A.',
  },
  {
    id: '12',
    nome: 'Limpeza de Cache',
    descricao: 'Limpar cache de sessões expiradas',
    dataExecucao: '2025-10-22T03:00:00',
    resultado: 'success',
    duracao: 10,
    tipo: 'cleanup',
    empresa: 'Digital First',
    distribuidora: 'Sul Distribuidora Ltda',
  },
  {
    id: '13',
    nome: 'Exportação de Dados Fiscais',
    descricao: 'Exportar dados para sistema fiscal',
    dataExecucao: '2025-10-22T02:30:00',
    resultado: 'success',
    duracao: 150,
    tipo: 'export',
    empresa: 'Commerce Plus',
    distribuidora: 'Nordeste Comércio e Distribuição',
  },
  {
    id: '14',
    nome: 'Importação de Notas Fiscais',
    descricao: 'Importar notas fiscais XML',
    dataExecucao: '2025-10-22T01:00:00',
    resultado: 'error',
    duracao: 40,
    mensagemErro: 'Arquivo XML malformado',
    tipo: 'import',
    empresa: 'Startup Inovadora',
    distribuidora: 'Norte Logística e Distribuição',
  },
  {
    id: '15',
    nome: 'Sincronização de Clientes',
    descricao: 'Sincronizar dados de clientes com CRM',
    dataExecucao: '2025-10-22T00:15:00',
    resultado: 'success',
    duracao: 75,
    tipo: 'sync',
    empresa: 'Empresa ABC',
    distribuidora: 'Centro-Oeste Distribuidora',
  },
  {
    id: '16',
    nome: 'Backup Completo',
    descricao: 'Backup completo semanal',
    dataExecucao: '2025-10-21T23:00:00',
    resultado: 'success',
    duracao: 450,
    tipo: 'backup',
    empresa: 'Tech Solutions',
    distribuidora: 'Distribuidora Nacional S.A.',
  },
  {
    id: '17',
    nome: 'Limpeza de Arquivos Temporários',
    descricao: 'Remover arquivos temporários antigos',
    dataExecucao: '2025-10-21T22:30:00',
    resultado: 'success',
    duracao: 25,
    tipo: 'cleanup',
    empresa: 'Commerce Plus',
    distribuidora: 'Sul Distribuidora Ltda',
  },
  {
    id: '18',
    nome: 'Processamento de Notificações',
    descricao: 'Enviar notificações pendentes',
    dataExecucao: '2025-10-21T21:45:00',
    resultado: 'error',
    duracao: 35,
    mensagemErro: 'Serviço de email temporariamente indisponível',
    tipo: 'sync',
    empresa: 'Digital First',
    distribuidora: 'Nordeste Comércio e Distribuição',
  },
  {
    id: '19',
    nome: 'Exportação de Inventário',
    descricao: 'Exportar dados de inventário',
    dataExecucao: '2025-10-21T20:00:00',
    resultado: 'success',
    duracao: 95,
    tipo: 'export',
    empresa: 'Startup Inovadora',
    distribuidora: 'Centro-Oeste Distribuidora',
  },
  {
    id: '20',
    nome: 'Sincronização de Distribuidoras',
    descricao: 'Atualizar dados das distribuidoras',
    dataExecucao: '2025-10-21T19:15:00',
    resultado: 'success',
    duracao: 55,
    tipo: 'sync',
    empresa: 'Empresa ABC',
    distribuidora: 'Norte Logística e Distribuição',
  },
];
